console.group("Group one");
console.log("Message one");
console.log("Message two");
console.group("Child group");
console.log("Message one");
console.log("Message two");
console.group("Grand Child group");
console.log("Message one");
console.log("Message two");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.group("Group two");
console.log("Message one");
console.log("Message two");
console.groupEnd();
